### ISSUE TITLE
Add extra fields to documentType

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-explorer#138]
I have now created @enonic/js-utils.detectValueType() so I can take a value at determine which valueType it ought to be configured as in the documentType.

Let's say one uses the Document REST API, or a Collector to persist a bunch of documents to explorer.
Some/most fields are already defined in a documentType, but there is a new unconfigured field (henceforth called extra field) in the documents being persisted.

In the first document the extra field looks like a geoPoint array,
but in the second document the same field is just an array of numbers.

If one updated the documentType after detecting geoPoint before trying to persist the second document,
the validation for the second document would fail.

Here are a couple solution ideas:

1. All extra fields are always added as 'string', and updated right away. An admin person can reconfigure and reindex. (handle reindex during/at the same time as a long running persist task?)

2. Keep some state during persist task, and pick the valueType which covers all instances of a extra field, don't update documentType before persist task is finished.

Side note: What should happen if an admin changes the documentType during persisting task?

So lets say
100 documents are already indexed.
Then some admin changes the documentType.
The document 101 and onward should use the new documentType, and the first 100 documents should be reindexed.
Since we don't have atomic commits, it could be a little tricky to figure out which documents needs to be reindexed.
Thus I think we need to store the documentType versionKey in the actual documents.
But even then lets say reindex is started, based on some query using versionKey=oldDocumentTypeVersion,
if the persist task is running at the same time, it might still store another document with the oldDocumentType.
We could delay the reindex a little using a runonce schedule, it would probably work ok in almost all cases. I guess without atomic commits, it's just impossible to guarantee.

**Comment by sigdestad** [comment]
I vote for alternative 1.

For the problem you describe, I see no big deal in reindexing everything when doctype is changed. We can optimise this later imho.
