### ISSUE TITLE
sanitize means collision in name on 'for' and 'før'

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-explorer#54]

**Comment by ComLock** [comment]
It should be a very rare problem that someone tried to create two
nodes with names so similar that asciifolding makes them identical.

This applies in the admin gui to
- collections
- fields
- stopWordLists
- thesauri
- synonyms
- interfaces

**Comment by ComLock** [comment]
This should not happen in the surgeon collector as the node names are a hash of the uri.

**Comment by alansemenov** [comment]
Closing until we face this issue
