### ISSUE TITLE
Use references within the config repo

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-explorer#59]
The only way to make safe delete is to use references everywhere within the config repo.

**Comment by ComLock** [comment]
You should not be able to

Delete a field
* that has fieldValues
* that is used in a collectionConfig or interface

Delete a fieldValue
* that is used in a collectionConfig or interface

Delete a stopWordList
* that is used in a interface

Delete a thesauri
* that is used in a interface

Delete a collection
* that is used in a interface

**Comment by alansemenov** [comment]
This should be in XP core - safe-delete on the node level
